export const MOCK_RESPONSE = {
  summoner: "Faker#KR1",
  region: "asia",
  role: "MIDDLE",
  tier: "CHALLENGER",
  patch: "15.10",
  rank: { tier: "CHALLENGER", division: "I", lp: 1547 },
  games_analyzed: 20,
  games_used: 19,
  outlier_games: 1,
  rank_changed: true,
  rank_direction: "up",
  patch_changed: false,
  summary: {
    cs_per_min: 8.2,
    vision_per_min: 1.05,
    deaths_per_game: 2.1,
    kill_participation: 72.4,
    damage_share: 31.5,
    winrate: 68.4,
    solo_deaths_early_avg: 0.3,
  },
  trends: {
    cs_per_min:         { rolling_10: 8.2,  rolling_20: 7.9,  direction: "improving" },
    vision_per_min:     { rolling_10: 1.05, rolling_20: 1.10, direction: "declining" },
    deaths:             { rolling_10: -2.1, rolling_20: -2.5, direction: "improving" },
    kill_participation: { rolling_10: 72.4, rolling_20: 70.1, direction: "improving" },
    damage_share:       { rolling_10: 31.5, rolling_20: 31.0, direction: "stable"    },
  },
  benchmark_deltas: {
    cs_per_min: {
      metric: "cs_per_min", player_value: 8.2,
      benchmark_p25: 7.5, benchmark_p50: 9.0, benchmark_p75: 10.5,
      quartile: "below", delta_vs_median: -0.8,
    },
    vision_per_min: {
      metric: "vision_per_min", player_value: 1.05,
      benchmark_p25: 0.95, benchmark_p50: 1.30, benchmark_p75: 1.75,
      quartile: "below", delta_vs_median: -0.25,
    },
    deaths: {
      metric: "deaths", player_value: 2.1,
      benchmark_p25: 1.8, benchmark_p50: 2.8, benchmark_p75: 4.2,
      quartile: "top", delta_vs_median: -0.7,
    },
    kill_participation: {
      metric: "kill_participation", player_value: 72.4,
      benchmark_p25: 58.0, benchmark_p50: 68.0, benchmark_p75: 77.0,
      quartile: "above", delta_vs_median: 4.4,
    },
  },
  benchmark: {
    champion: "Azir",
    role: "MIDDLE",
    tier: "CHALLENGER",
    patch: "15.10",
    source: "opgg",
    sample_size: 38400,
    winrate: 51.2,
    stale: false,
    cs_per_min:           { p25: 7.5, p50: 9.0, p75: 10.5 },
    vision_score_per_min: { p25: 0.95, p50: 1.30, p75: 1.75 },
    deaths_per_game:      { p25: 1.8, p50: 2.8, p75: 4.2 },
    kill_participation:   { p25: 58.0, p50: 68.0, p75: 77.0 },
  },
  coaching: {
    primary_focus: "Improve CS efficiency — you're below median for your tier",
    summary: "Your death rate and KP are solid but CS is lagging behind top Challenger players by ~0.8/min. Vision is declining over the last 10 games — prioritize control wards on every back. Overall trajectory is positive: you're dying less and participating more.",
    flags: ["rank_up"],
    coaching_points: [
      {
        metric: "cs_per_min",
        quartile: "below",
        trend: "improving",
        suggestion: "You're trending up on CS but still below median. Focus on wave management in the first 15 minutes — freeze under tower to deny enemy CS while maintaining yours.",
      },
      {
        metric: "vision_per_min",
        quartile: "below",
        trend: "declining",
        suggestion: "Buy one control ward every back and place it in the river bush near mid. Vision declining 10% over last 10 games is a habit breaking down — enforce it consciously.",
      },
    ],
    confidence: 0.88,
  },
  active_mistakes: [
    {
      id: 1,
      metric: "cs_per_min",
      description: "CS ниже медианы уровня",
      severity: "minor",
      sessions_present: 4,
      sessions_absent: 0,
      role: "MIDDLE",
    },
    {
      id: 2,
      metric: "vision_per_min",
      description: "Vision score ниже медианы уровня",
      severity: "moderate",
      sessions_present: 7,
      sessions_absent: 0,
      role: "MIDDLE",
    },
  ],
}
